-- ElevenLabs voice IDs selected via MCP on 2026-04-07
-- All voices are premade voices from the account's library.
-- Sample files: tmp/elevenlabs-mcp-output/
-- Model used for samples: eleven_multilingual_v2
--
-- NOTE: Run this AFTER migration 009_add_live_guide has been applied.
-- NOTE: DO NOT run automatically — review samples first.
-- NOTE: guide_voices.id are UUIDs generated by the DB at seed time;
--       this script matches rows by (style_group, language) which is UNIQUE.

-- academic / en — Alice (Clear, Engaging Educator)
-- Formal, measured British-adjacent accent. Works well for cultural/historical narration.
-- Sample: tmp/elevenlabs-mcp-output/academic_en_alice.mp3
UPDATE guide_voices
SET elevenlabs_voice_id = 'Xb7hH8MSUJpSbSDYk0k2'
WHERE style_group = 'academic' AND language = 'en';

-- academic / ru — Daniel (Steady Broadcaster)
-- Deep, composed delivery. eleven_multilingual_v2 produces clear Russian with this voice.
-- Sample: tmp/elevenlabs-mcp-output/academic_ru_daniel.mp3
UPDATE guide_voices
SET elevenlabs_voice_id = 'onwK4e9ZLuTAKqWW03F9'
WHERE style_group = 'academic' AND language = 'ru';

-- friendly / en — Jessica (Playful, Bright, Warm)
-- Energetic and approachable. Natural "friend showing you around" feel.
-- Sample: tmp/elevenlabs-mcp-output/friendly_en_jessica.mp3
UPDATE guide_voices
SET elevenlabs_voice_id = 'cgSgspJ2msm6clMCkdW9'
WHERE style_group = 'friendly' AND language = 'en';

-- friendly / ru — Matilda (Knowledgeable, Professional, Upbeat)
-- Warm and engaging in Russian. Upbeat enough for friendly style without sounding robotic.
-- Sample: tmp/elevenlabs-mcp-output/friendly_ru_matilda.mp3
UPDATE guide_voices
SET elevenlabs_voice_id = 'XrExE9yKIg1WjnnlVkGX'
WHERE style_group = 'friendly' AND language = 'ru';

-- dramatic / en — George (Warm, Captivating Storyteller)
-- narrative_story use_case, mature British voice. Best dramatic delivery in the library.
-- Sample: tmp/elevenlabs-mcp-output/dramatic_en_george.mp3
UPDATE guide_voices
SET elevenlabs_voice_id = 'JBFqnCBsd6RMkjVDRZzb'
WHERE style_group = 'dramatic' AND language = 'en';

-- dramatic / ru — Brian (Deep, Resonant and Comforting)
-- Deep resonant voice; produces excellent tension/drama in Russian with style_exaggeration.
-- Sample: tmp/elevenlabs-mcp-output/dramatic_ru_brian.mp3
UPDATE guide_voices
SET elevenlabs_voice_id = 'nPczCjzI2devNBz1zQrb'
WHERE style_group = 'dramatic' AND language = 'ru';

-- minimal / en — River (Relaxed, Neutral, Informative)
-- Neutral gender, calm delivery. Perfect for concise factual annotations.
-- Sample: tmp/elevenlabs-mcp-output/minimal_en_river.mp3
UPDATE guide_voices
SET elevenlabs_voice_id = 'SAz9YHcvj6GT2YYXdXww'
WHERE style_group = 'minimal' AND language = 'en';

-- minimal / ru — Eric (Smooth, Trustworthy)
-- Clean and classy; in Russian sounds precise and unobtrusive — ideal for brief mode.
-- Sample: tmp/elevenlabs-mcp-output/minimal_ru_eric.mp3
UPDATE guide_voices
SET elevenlabs_voice_id = 'cjVigY5qzO86Huf0OWal'
WHERE style_group = 'minimal' AND language = 'ru';

-- Verify result:
SELECT name, style_group, language, elevenlabs_voice_id
FROM guide_voices
ORDER BY style_group, language;
