"""
Pydantic schemas for the AI Hotel Picker module.

Split into two groups:
  1. API schemas  — request/response models exposed via HTTP endpoints
  2. Pipeline schemas — internal models used between pipeline components
"""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, model_validator


# =============================================================================
# Scoring & Intent
# =============================================================================

class ScoringWeights(BaseModel):
    """
    Dynamic per-request ranking weights generated by IntentParser.
    All values in [0, 1], sum must equal 1.0 (auto-normalised).
    """
    semantic_match: float = 0.20   # atmosphere / style / concept match
    segment_fit: float = 0.20      # review scores for this traveller type
    facility_match: float = 0.20   # must_have + nice_to_have facilities
    review_quality: float = 0.20   # review sentiment, absence of hidden issues
    price_value: float = 0.10      # price-to-value ratio
    location: float = 0.10         # distance to centre / preferred area

    @model_validator(mode="after")
    def normalize(self) -> "ScoringWeights":
        total = (
            self.semantic_match + self.segment_fit + self.facility_match
            + self.review_quality + self.price_value + self.location
        )
        if total > 0 and abs(total - 1.0) > 0.01:
            factor = 1.0 / total
            self.semantic_match *= factor
            self.segment_fit *= factor
            self.facility_match *= factor
            self.review_quality *= factor
            self.price_value *= factor
            self.location *= factor
        return self


DEFAULT_WEIGHTS = ScoringWeights(
    semantic_match=0.20,
    segment_fit=0.20,
    facility_match=0.20,
    review_quality=0.20,
    price_value=0.10,
    location=0.10,
)


class ParsedIntent(BaseModel):
    """
    Structured output of IntentParser (Phase 1).
    Combines deterministic request params + LLM-derived semantic analysis.
    """
    # --- API filter params ---
    api_filters: list[str] = Field(
        default_factory=list,
        description='Combined user + LLM filters, e.g. ["facility::107", "room_facility::23"]',
    )
    # User-specified filters only (from request.amenities/property_types) — never dropped in cascade
    user_api_filters: list[str] = Field(default_factory=list)
    price_min: float | None = None
    price_max: float | None = None
    sort_by: str = "bayesian_review_score"
    min_review_score: float = 7.0

    # --- LLM-derived semantic ---
    semantic_criteria: dict[str, list[str]] = Field(
        default_factory=dict,
        description='e.g. {atmosphere: ["quiet", "romantic"]}',
    )
    must_have: list[str] = Field(default_factory=list)
    dealbreakers: list[str] = Field(default_factory=list)

    # --- Traveller profile ---
    user_segment: str = "couple"   # couple|family|business|solo|group
    children_ages: list[int] = Field(default_factory=list)
    is_remote_work: bool = False
    is_boutique_preferred: bool = False
    implicit_needs: list[str] = Field(default_factory=list)

    # --- Constraints from HotelSearchRequest (propagated for cascade use) ---
    stars_min: int | None = None
    prefers_free_cancellation: bool = False  # soft bonus, NOT hard API filter

    # --- City name normalized for Booking.com API (LLM or unicode fallback) ---
    city_for_booking: str = ""

    # --- Dynamic scoring weights (sum=1.0, auto-normalised) ---
    scoring_weights: ScoringWeights = Field(default_factory=ScoringWeights)


# =============================================================================
# API Request / Response schemas
# =============================================================================

class HotelSearchRequest(BaseModel):
    city: str
    check_in: str = Field(description="YYYY-MM-DD")
    check_out: str = Field(description="YYYY-MM-DD")
    adults: int = Field(default=2, ge=1, le=30)
    children_ages: list[int] | None = Field(default_factory=list)
    budget_min: float | None = None
    budget_max: float | None = None
    currency: str = "EUR"
    stars_min: int | None = Field(default=None, ge=1, le=5)
    user_wishes: str | None = None    # free-text input for IntentParser
    amenities: list[str] | None = Field(
        default_factory=list,
        description='UI checkbox selections, e.g. ["facility::107", "room_facility::23"]',
    )
    property_types: list[str] | None = Field(
        default_factory=list,
        description='e.g. ["property_type::204"]',
    )
    meal_plan: str | None = None
    free_cancellation: bool | None = False
    adults_only: bool | None = False
    pets_allowed: bool | None = False
    session_id: str | None = None    # present when paginating
    offset: int = 0

    @model_validator(mode="after")
    def coerce_nulls(self) -> "HotelSearchRequest":
        """Convert None → default for fields that iOS may send as null."""
        if self.children_ages is None:
            self.children_ages = []
        if self.amenities is None:
            self.amenities = []
        if self.property_types is None:
            self.property_types = []
        if self.free_cancellation is None:
            self.free_cancellation = False
        if self.adults_only is None:
            self.adults_only = False
        if self.pets_allowed is None:
            self.pets_allowed = False
        return self


class HotelFindRequest(BaseModel):
    hotel_name: str
    city: str | None = None
    check_in: str | None = None
    check_out: str | None = None
    adults: int = 2
    currency: str = "EUR"


class HotelResult(BaseModel):
    hotel_id: int
    name: str
    accommodation_type: str
    stars: int = Field(ge=0, le=5)
    is_boutique: bool = False   # no chaincode + niche property
    url: str

    # Ratings
    review_score: float
    review_score_word: str
    review_count: int
    category_scores: dict[str, float] = Field(
        default_factory=dict,
        description="{cleanliness, comfort, location, staff, value, wifi}",
    )
    segment_scores: dict[str, float] = Field(
        default_factory=dict,
        description="{couple: 8.9, family: 7.2, business: 8.5}",
    )

    # Price
    price_per_night: float
    total_price: float
    currency: str
    strikethrough_price: float | None = None

    # Location
    address: str
    district: str | None = None
    distance_to_center_km: float
    latitude: float
    longitude: float

    # Facilities & photos
    photos: list[str] = Field(
        default_factory=list,
        description="All hotel photo URLs from Booking.com in original order",
    )
    key_facilities: list[str] = Field(
        default_factory=list,
        description='e.g. ["Free WiFi", "Pool", "Spa"]',
    )
    breakfast_included: bool = False
    pets_allowed: bool = False
    free_cancellation: bool = False
    checkin_from: str = ""
    checkout_until: str = ""

    # Booking
    booking_url: str = ""   # deep link with pre-filled dates, guests, currency

    # AI insights
    ai_score: float = Field(ge=0, le=10)
    ai_match_reason: str = ""
    ai_pros: list[str] = Field(default_factory=list)
    ai_cons: list[str] = Field(default_factory=list)
    ai_hidden_issues: list[str] = Field(default_factory=list)
    review_summary: str = ""

    # Vision (top-5 only, optional)
    interior_style: str | None = None
    view_quality: str | None = None
    visual_cleanliness: str | None = None


class ExcludedHotel(BaseModel):
    """Near-miss hotel that scored but didn't make the top-10."""
    hotel_id: int
    name: str
    stars: int
    review_score: float
    price_per_night: float
    ai_score: float
    reason: str   # e.g. "Family traveller rating 6.2 — below average"


class HotelSearchResponse(BaseModel):
    hotels: list[HotelResult]
    notable_excluded: list[ExcludedHotel] = Field(
        default_factory=list,
        description="3–5 near-miss hotels with explanation",
    )
    city: str
    check_in: str
    check_out: str
    total_found: int
    session_id: str
    applied_filters_summary: str = ""
    has_more: bool = False


class HotelExplainRequest(BaseModel):
    session_id: str
    hotel_name: str


class HotelExplanationResponse(BaseModel):
    hotel_id: int | None = None
    hotel_name: str
    found_in_candidates: bool
    reason: str
    ai_score: float | None = None


# =============================================================================
# Pipeline-internal schemas (not exposed via HTTP)
# =============================================================================

class DestinationResult(BaseModel):
    """Result of BookingClient.search_destination()."""
    dest_id: str          # e.g. "-1456928"  (string, may be negative)
    search_type: str      # "city" | "district" | "landmark" | "airport" | "region"
    name: str
    country: str = ""
    label: str = ""
    latitude: float | None = None
    longitude: float | None = None
    nr_hotels: int = 0


class ReviewRaw(BaseModel):
    """Single raw review entry from getHotelReviews."""
    review_hash: str = ""
    pros: str = ""
    cons: str = ""
    title: str = ""
    hotelier_response: str = ""
    author_type: str = ""   # "solo_traveller" | "couple" | "family_with_young_children" | etc.
    average_score: float | None = None


class ReviewScores(BaseModel):
    """Category scores from getHotelReviewScores."""
    cleanliness: float | None = None
    comfort: float | None = None
    location: float | None = None
    staff: float | None = None
    value: float | None = None
    wifi: float | None = None
    facilities: float | None = None
    # Scores broken down by traveller type (from category_type entries)
    by_segment: dict[str, float] = Field(
        default_factory=dict,
        description="e.g. {couple: 8.9, family_with_young_children: 7.2}",
    )


class FacilityItem(BaseModel):
    """Single facility from getHotelFacilities."""
    id: int
    group_id: int
    title: str
    charge_mode: str = "UNKNOWN_CHARGE_MODE"   # "FREE" | "PAID" | "UNKNOWN_CHARGE_MODE"


class HotelRawData(BaseModel):
    """
    Aggregated raw data for one hotel collected in Phase 3
    (5 parallel API calls via BookingClient.fetch_hotel_full_data).
    """
    hotel_id: int

    # From getHotelDetails
    details: dict[str, Any] = Field(default_factory=dict)
    name: str = ""
    url: str = ""
    latitude: float | None = None
    longitude: float | None = None
    address: str = ""
    city: str = ""
    district: str | None = None
    distance_to_cc: float = 0.0
    accommodation_type: str = ""
    stars: int = 0
    is_sold_out: bool = False
    price_per_night: float = 0.0
    total_price: float = 0.0
    currency: str = "EUR"
    breakfast_included: bool = False
    checkin_from: str = ""
    checkout_until: str = ""
    chaincode: str | None = None   # present → chain hotel (not boutique)
    property_highlights: list[str] = Field(default_factory=list)
    top_benefits: list[str] = Field(default_factory=list)
    wifi_score: float | None = None
    free_cancellation: bool = False

    # From getHotelReviewScores
    review_scores: ReviewScores = Field(default_factory=ReviewScores)
    review_score: float = 0.0
    review_count: int = 0

    # From getHotelReviews page=1 + page=2 (combined, 20 reviews)
    reviews: list[ReviewRaw] = Field(default_factory=list)

    # From getHotelFacilities
    facilities: list[FacilityItem] = Field(default_factory=list)

    # Room photo URLs extracted from getHotelDetails.rooms (no extra API call)
    photo_urls: list[str] = Field(default_factory=list)


class ReviewAnalysis(BaseModel):
    """Output of ReviewAnalyzer for one hotel."""
    hotel_id: int
    top_pros: list[str] = Field(default_factory=list)
    top_cons: list[str] = Field(default_factory=list)
    hidden_issues: list[str] = Field(default_factory=list)
    trend: str = "stable"   # "quality_improving" | "declining" | "stable"
    segment_fit: float = 0.5    # 0–1 for the requested user_segment
    segment_highlights: list[str] = Field(default_factory=list)


class HotelProfile(BaseModel):
    """
    Combined hotel profile for MasterRanker (Phase 5).
    Merges HotelRawData + ReviewAnalysis.
    """
    raw: HotelRawData
    review_analysis: ReviewAnalysis

    @property
    def hotel_id(self) -> int:
        return self.raw.hotel_id


class HotelRanked(BaseModel):
    """Single ranked hotel entry from MasterRanker."""
    hotel_id: int
    ai_score: float
    ai_match_reason: str = ""
    why_this_hotel: list[str] = Field(default_factory=list)


class MasterRankingResult(BaseModel):
    """Full output of MasterRanker (Phase 5)."""
    ranked_top10: list[HotelRanked]
    filtered_out: dict[str, str] = Field(
        default_factory=dict,
        description="hotel_id (str) → short exclusion reason from LLM",
    )
    notable_excluded: list[ExcludedHotel] = Field(
        default_factory=list,
        description="3–5 near-miss hotels with ai_score and reason",
    )


class PhotoAnalysis(BaseModel):
    """Output of PhotoAnalyzer for one hotel (Phase 6, optional vision)."""
    interior_style: str = "mixed"          # modern | classic | boutique | rustic | mixed
    cleanliness_visual: str = "average"    # excellent | good | average | poor
    view_quality: str = "none"             # sea | city | garden | parking | none | mixed
    room_size_estimate: str = "standard"   # spacious | standard | compact
    style_tags: list[str] = Field(default_factory=list)
    photo_match_score: float = 0.5         # 0–1, match with user's semantic_criteria


class SearchMoreRequest(BaseModel):
    """Request body for POST /api/hotels/search/more."""
    session_id: str
