import Header from '../components/layout/Header'
import Footer from '../components/layout/Footer'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-base flex flex-col">
      <Header />
      <main className="flex-1 pt-24 pb-16 px-6">
        <article className="max-w-3xl mx-auto prose-invert">
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-text-muted text-sm mb-8">Last updated: March 1, 2025</p>

          <div className="space-y-6 text-text-secondary text-sm leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing or using Locally ("the Service"), operated by <strong className="text-white">BUDOVSKY ONLINE - FZCO</strong>, a company registered in Dubai Silicon Oasis, Dubai, United Arab Emirates ("the Company", "we", "us"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
              <p>
                Locally is an AI-powered travel planning platform that generates personalized itineraries based on your preferences. The Service includes trip planning, route optimization, accommodation recommendations, and related travel tools.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">3. User Accounts</h2>
              <ul className="list-disc list-inside space-y-1">
                <li>You may use limited features as a guest or create an account for full access.</li>
                <li>You are responsible for maintaining the security of your account credentials.</li>
                <li>You must provide accurate information when creating an account.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">4. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside mt-2 space-y-1">
                <li>Use the Service for any unlawful purpose.</li>
                <li>Attempt to gain unauthorized access to the Service or its systems.</li>
                <li>Scrape, crawl, or use automated means to access the Service without permission.</li>
                <li>Interfere with or disrupt the Service infrastructure.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">5. AI-Generated Content</h2>
              <p>
                Itineraries and recommendations generated by Locally are created using artificial intelligence and third-party data sources. While we strive for accuracy, we do not guarantee that all information (opening hours, prices, availability) is current or correct. Users should verify important details independently before travel.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">6. Third-Party Services</h2>
              <p>
                The Service integrates with third-party providers including Google Maps, Booking.com, and AI providers. Your use of these integrated services is subject to their respective terms and privacy policies. We are not responsible for the content or practices of third-party services.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">7. Intellectual Property</h2>
              <p>
                The Service, including its design, code, and AI models, is the property of BUDOVSKY ONLINE - FZCO. You retain ownership of content you create (trip preferences, notes). By using the Service, you grant us a license to process your input data to generate itineraries.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">8. Limitation of Liability</h2>
              <p>
                The Service is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to travel disruptions, incorrect information, or service interruptions.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">9. Termination</h2>
              <p>
                We reserve the right to suspend or terminate your access to the Service at any time for violation of these Terms. You may delete your account at any time by contacting us.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">10. Changes to Terms</h2>
              <p>
                We may modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">11. Contact</h2>
              <p>For questions about these Terms, contact us:</p>
              <ul className="list-none mt-2 space-y-1">
                <li><strong className="text-white">BUDOVSKY ONLINE - FZCO</strong></li>
                <li>Dubai Silicon Oasis, Dubai, United Arab Emirates</li>
                <li>Phone: <a href="tel:+971521173919" className="text-primary hover:underline">+971 52 117 3919</a></li>
                <li>Email: <a href="mailto:locally.office@gmail.com" className="text-primary hover:underline">locally.office@gmail.com</a></li>
              </ul>
            </section>
          </div>
        </article>
      </main>
      <Footer />
    </div>
  )
}
